/* ============================================================
   Michis en pixel art · 32x32 a color
   GENERADO por pixel/generar_michis.py — no editar a mano.

   Cada sprite son 32 cadenas de 32 caracteres. Cada carácter es un
   color de PALETA; '.' es transparente.
   ============================================================ */

export const PALETA = {
  o: '#4A2C1A',  // contorno
  n: '#F5923E',  // naranja
  N: '#D6702A',  // naranja oscuro (rayas)
  c: '#FFF3E0',  // crema
  r: '#FF9BB0',  // rosa
  k: '#3A2620',  // ojos
  w: '#FFFFFF',  // brillo
};

export const TAM = 32;
export const ESTADOS = ['esqueletico', 'gordo', 'kawaii', 'fit', 'hipertrofiado'];

export const MICHIS = {
  esqueletico: [
    '......oo................oo......',
    '.....onno..............onno.....',
    '.....orrro............orrro.....',
    '.....orrrro..........orrrro.....',
    '.....onnnnnoooooooooonnnnno.....',
    '....onnnnnnNNNnnNNNnnNNNnnno....',
    '....onnnnkwwknnnnnnkwwknnnno....',
    '....onnnnkwkknnnnnnkwkknnnno....',
    '....onnnnkkkknnnnnnkkkknnnno....',
    '....orrrnnkkknnnnnnkkknnrrro....',
    '....orrrnnnnnnnnnnnnnnnnrrro....',
    '....onrrnnnncccrrcccnnnnrrno....',
    '.....onnnnnnncoccocnnnnnnno.....',
    '......oonnnnnncoocnnnnnnoo......',
    '........ooooonnccnnooooo........',
    '.............onnnno.............',
    '..............onno..............',
    '.............onnnno.............',
    '..........o.onnnnnno.o..........',
    '..........o.oooooooo.o..........',
    '..........o.onnnnnno.o..........',
    '..........o.oooooooo.o..........',
    '............onccccno............',
    '............ooccccoo...ooo......',
    '............onnnnnno..ooo.......',
    '............onnnnnnnooo.........',
    '............onnoonno............',
    '...........oooo..oooo...........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  gordo: [
    '......oo................oo......',
    '.....onno..............onno.....',
    '.....orrro............orrro.....',
    '.....orrrro..........orrrro.....',
    '.....onnnnnoooooooooonnnnno.....',
    '....onnnnnnNNNnnNNNnnNNNnnno....',
    '....onnnnkwwknnnnnnkwwknnnno....',
    '....onnnnkwkknnnnnnkwkknnnno....',
    '....onnnnkkkknnnnnnkkkknnnno....',
    '....orrrnnkkknnnnnnkkknnrrro....',
    '....orrrnnnnnnnnnnnnnnnnrrro....',
    '....onrrnnnncccrrcccnnnnrrno....',
    '.....onnnnnnncoccocnnnnnnno.....',
    '......oonnnnnncoocnnnnnnoo......',
    '........ooooonnccnnooooo........',
    '.............onnnno.............',
    '...........oonnnnnnoo...........',
    '.........oonnnnnnnnnnoo.........',
    '.......oonnnnnnnnnnnnnnoo.......',
    '.....ooNNNNnnnnnnnnnnnNNNNo.....',
    '....onnnnnnccccccccccnnnnnno....',
    '....onNNNNnccccccccccnnNNNNo....',
    '....onnnnnnccccccccccnnnnnnnooo.',
    '.....oonnnnnccccccccnnnnnnnnoo..',
    '.......oonnnnccccccnnnnooooo....',
    '.........onnnnnnnnnnnno.........',
    '..........onnnoooonnno..........',
    '.........ooooo....ooooo.........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  kawaii: [
    '......oo................oo......',
    '.....onno..............onno.....',
    '.....orrro............orrro.....',
    '.....orrrro..........orrrro.....',
    '.....onnnnnoooooooooonnnnno.....',
    '....onnnnnnNNNnnNNNnnNNNnnno....',
    '....onnnnkwwknnnnnnkwwknnnno....',
    '....onnnnkwkknnnnnnkwkknnnno....',
    '....onnnnkkkknnnnnnkkkknnnno....',
    '....orrrnnkkknnnnnnkkknnrrro....',
    '....orrrnnnnnnnnnnnnnnnnrrro....',
    '....onrrnnnncccrrcccnnnnrrno....',
    '.....onnnnnnncoccocnnnnnnno.....',
    '......oonnnnnncoocnnnnnnoo......',
    '........ooooonnccnnooooo........',
    '.............onnnno.............',
    '...........oonnnnnnoo...........',
    '..........onnnnnnnnnno..........',
    '.........onNNNnnnnnNNNo.........',
    '.........onnnnnnnnnnnno.........',
    '.........onNNccccccNNNo.........',
    '.........onnnccccccnnno.........',
    '.........onnnccccccnnno..oo.....',
    '..........onnnccccnnno...ono....',
    '..........onnnnnnnnnno..ooo.....',
    '..........onnnnnnnnnnnooo.......',
    '..........onnnoooonnno..........',
    '.........ooooo....ooooo.........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  fit: [
    '......oo................oo......',
    '.....onno..............onno.....',
    '.....orrro............orrro.....',
    '.....orrrro..........orrrro.....',
    '.....onnnnnoooooooooonnnnno.....',
    '....onnnnnnNNNnnNNNnnNNNnnno....',
    '....onnnnkwwknnnnnnkwwknnnno....',
    '....onnnnkwkknnnnnnkwkknnnno....',
    '....onnnnkkkknnnnnnkkkknnnno....',
    '....orrrnnkkknnnnnnkkknnrrro....',
    '....orrrnnnnnnnnnnnnnnnnrrro....',
    '....onrrnnnncccrrcccnnnnrrno....',
    '.....onnnnnnncoccocnnnnnnno.....',
    '......oonnnnnncoocnnnnnnoo......',
    '........ooooonnccnnooooo........',
    '.............onnnno.............',
    '...........oonnnnnnoo...........',
    '..........onnnnnnnnnno..........',
    '......oo.onNNNnnnnnNNNo.oo......',
    '......oo.onnnnccccnnnno.oo......',
    '......oo.onnnnccccnnnno.oo......',
    '..........onnnccccnnno..........',
    '...........onnccccnno...........',
    '...........onnnnnnnno....ooo....',
    '..........onNNNnnnNNNo..ooo.....',
    '..........onnnnnnnnnnnooo.......',
    '..........onnnoooonnno..........',
    '.........ooooo....ooooo.........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  hipertrofiado: [
    '......oo................oo......',
    '.....onno..............onno.....',
    '.....orrro............orrro.....',
    '.....orrrro..........orrrro.....',
    '.....onnnnnoooooooooonnnnno.....',
    '....onnnnnnNNNnnNNNnnNNNnnno....',
    '....onnnnkwwknnnnnnkwwknnnno....',
    '....onnnnkwkknnnnnnkwkknnnno....',
    '....onnnnkkkknnnnnnkkkknnnno....',
    '....orrrnnkkknnnnnnkkknnrrro....',
    '....orrrnnnnnnnnnnnnnnnnrrro....',
    '....onrrnnnncccrrcccnnnnrrno....',
    '.....onnnnnnncoccocnnnnnnno.....',
    '......oonnnnnncoocnnnnnnoo......',
    '........ooooonnccnnooooo........',
    '.............onnnno.............',
    '...........oonnnnnnoo...........',
    '..........onnnnnnnnnno..........',
    '....oooooonnnnnnnnnnnnoooooo....',
    '...onNNnnnnnnnccccnnnnnnnnNNo...',
    '...onnnnnonnnnccccnnnnonnnnno...',
    '....oNNno.onnnccccnnno.onnNN....',
    '.....oooo..onnnnnnnno..oooo.....',
    '...........onnnnnnnno...........',
    '..........onNNNnnnNNNo..ooo.....',
    '..........onnnnnnnnnnnooo.......',
    '..........onnnoooonnno..........',
    '.........ooooo....ooooo.........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
};
